# -*- coding: utf-8 -*-
"""WEEK6_00000034000_WILLIBRORDUSBAYU.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hfWiB3ovBOsGM4a6bM0yB5A7-Et4HI6U
"""

#!/usr/bin/env python
# coding: utf-8

get_ipython().system('python --version')

get_ipython().system('pip install opencv-python')

get_ipython().system('apt update && apt install -y libsm6 libxext6')

get_ipython().run_line_magic('matplotlib', 'inline')

import urllib.request as urllib2

def upload_files():
  from google.colab import files
  uploaded = files.upload()
  for k, v in uploaded.items():
    open(k, 'wb').write(v)
  return list(uploaded.keys())

fileGambar = upload_files()
xmldata = urllib2.urlopen('https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_frontalface_default.xml').read()
file = open('haarcascade_frontalface_default.xml', 'wb')
file.write(xmldata)
file.close()

import os
import cv2
from matplotlib import pyplot as plt
import urllib.request as urllib2
import numpy as np

def dimensiGambar(image):
  print("Dimensi: tinggi="+str(image.shape[0])+"px, lebar="+str(image.shape[1])+"px, kanal warna="+str(image.shape[2]))

def warnaKeGray(image):
  return cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

def BGRKeRGB(image):
  return cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

def cariMuka(image):
  face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
  gray = warnaKeGray(image)
  faces = face_cascade.detectMultiScale(gray, scaleFactor=1.3, minNeighbors=2, minSize=(30,30), flags = cv2.CASCADE_SCALE_IMAGE)
  print("Ketemu "+str(len(faces)) + " muka")
  for (x, y, w, h) in faces:
    cv2.rectangle(image, (x,y), (x+w, y+h), (0,255,0), 5)
  tampilkanGambar(BGRKeRGB(image))

def tampilkanGambar(image):
  plt.imshow(image)
  plt.grid(False)
  plt.axis('off')
  plt.show()

gambar = cv2.imread(os.getcwd()+'/selfie.jpg')
dimensiGambar(gambar)
print("Gambar asli:")
tampilkanGambar(BGRKeRGB(gambar))
print("Gambar BGR hasil loading openCV:")
tampilkanGambar(gambar)
print("Gambar grayscale: ")
tampilkanGambar(warnaKeGray(gambar))

print("Cari muka: ")
cariMuka(gambar)
print("Selesai")

#CHALLENGE
def cariMuka(image):
  face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
  gray = warnaKeGray(image)
  faces = face_cascade.detectMultiScale(gray, scaleFactor=1.3, minNeighbors=2, minSize=(30,30), flags=cv2.CASCADE_SCALE_IMAGE)
  print ("Ketemu " + str(len(faces)) + " muka")
  for (x,y,w,h) in faces:
    cv2.rectangle(image, (x,y),(x+w,y+h),(0,225,0),5)
  tampilkanGambar(BGRKeRGB(image))

cariMuka(gambar)